Common page for all components
js-tasks-ru/htmlcss-20220317_maksim96 pull request #3
Opened 2022-03-23 14:55 UTC by mshumako

2022-03-24 09:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-24 14:35 UTC, GSemikozov requested changes

2022-03-24 14:35 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__space-after {
модификатор? причем модификатор .footer__title? Тогда .footer__title_space_after

2022-03-31 15:54 UTC, GSemikozov approved these changes

2022-03-31 15:54 UTC, merged