Styles for accordion component
js-tasks-ru/htmlcss-20220317_maksim96 pull request #5
Opened 2022-03-24 11:20 UTC by mshumako

2022-03-24 11:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-30 18:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-30 19:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-30 19:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-30 20:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-31 15:56 UTC, GSemikozov requested changes

2022-03-31 15:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 32px;
в макете так же?)

2022-03-31 15:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content_position {
лучше не через модификатор, а сразу в .accordion__content (в элементах марджины можно задавать, и логика отображения здесь без вариаций)

2022-04-01 20:05 UTC, GSemikozov approved these changes

2022-04-01 20:05 UTC, merged